env:
  global:
    - CI_NAME=travis-pro
    - COVERALLS_REPO_TOKEN=vdNMahpXoUgQzh3vElwFHtggK1yA374n4

language: java
jdk:
  - oraclejdk8          // tells Travis to use Java 8

after_success:
  - gradle jacocoTestReport coveralls
